import React, { useState, useEffect } from "react";
import api from "../../../utils/api";
import { toast } from "react-toastify";
import { jsPDF } from "jspdf";
import { useSearch } from "../../../context/SearchContext";

const AdminReports = () => {
    const { searchTerm } = useSearch();
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [responseForm, setResponseForm] = useState({ id: null, status: "", response: "" });

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {
        try {
            setLoading(true);
            const res = await api.get("/reports");
            setReports(res.data.reports);
        } catch (err) {
            console.error("Error fetching reports:", err);
        } finally {
            setLoading(false);
        }
    };

    const downloadPDF = (report) => {
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(40, 167, 69); // Success Green
        doc.text("Waste Management Weekly Report", 105, 20, { align: "center" });
        
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 25, 190, 25);
        
        // Report Details
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(`Title: ${report.title}`, 20, 40);
        doc.text(`Municipal Corp: ${report.mcName}`, 20, 50);
        doc.text(`Location: ${report.city}, ${report.district}`, 20, 60);
        doc.text(`Submission Date: ${new Date(report.createdAt).toLocaleDateString()}`, 20, 70);
        doc.text(`Current Status: ${report.status}`, 20, 80);

        doc.line(20, 85, 190, 85);

        // Performance Stats
        doc.setFontSize(16);
        doc.text("Operational Statistics", 20, 100);
        doc.setFontSize(12);
        doc.text(`• Tasks Completed: ${report.tasksCompleted}`, 30, 110);
        doc.text(`• Pending Tasks: ${report.pendingTasks}`, 30, 120);
        doc.text(`• Field Workers Involved: ${report.workersInvolved}`, 30, 130);

        // Description
        doc.setFontSize(16);
        doc.text("Summary / Description", 20, 150);
        doc.setFontSize(11);
        const splitDescription = doc.splitTextToSize(report.description || "No description provided.", 160);
        doc.text(splitDescription, 20, 160);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Environs Smart Waste Management System", 105, 280, { align: "center" });

        doc.save(`${report.mcName}_Report_${report._id.substring(0, 5)}.pdf`);
    };

    const handleRespond = async (e) => {
        e.preventDefault();
        try {
            const res = await api.patch(`/reports/${responseForm.id}/respond`, {
                status: responseForm.status,
                adminResponse: responseForm.response
            });
            if (res.data.success) {
                toast.success("Response submitted successfully!");
                setResponseForm({ id: null, status: "", response: "" });
                fetchReports();
            }
        } catch (err) {
            toast.error("Failed to submit response.");
        }
    };

    const handleDelete = async (id) => {
        if (!window.confirm("Are you sure you want to delete this report? This action cannot be undone.")) return;
        try {
            const res = await api.delete(`/reports/${id}`);
            if (res.data.success) {
                toast.success("Report deleted successfully.");
                fetchReports();
            }
        } catch (err) {
            toast.error("Failed to delete report.");
        }
    };

    const filteredReports = (reports || []).filter(report => 
        Object.values(report).some(val => 
            String(val).toLowerCase().includes(searchTerm.toLowerCase())
        )
    );

    return (
        <div className="dashboard-section-wrap p-4">
            <header className="mb-4">
                <h2 className="fw-bold">Review Municipal Reports</h2>
                <p className="text-muted">Validate and respond to weekly performance reports from zones.</p>
            </header>

            <div className="dashboard-card p-0 overflow-hidden shadow-sm border-0 bg-white">
                <div className="table-responsive">
                    <table className="table table-hover align-middle mb-0">
                        <thead className="table-light">
                            <tr>
                                <th className="ps-4">MC Name</th>
                                <th>City / Zone</th>
                                <th>Stats (Comp/Pend)</th>
                                <th>Status</th>
                                <th className="pe-4 text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {loading ? (
                                <tr><td colSpan={5} className="text-center py-5">Loading reports...</td></tr>
                            ) : filteredReports.length === 0 ? (
                                <tr><td colSpan={5} className="text-center text-muted py-5">No matching results found.</td></tr>
                            ) : (
                                filteredReports.map((report) => (
                                    <tr key={report._id}>
                                        <td className="ps-4">
                                            <div className="fw-bold text-primary">{report.title || report.mcName}</div>
                                            <div className="small text-muted">{report.mcName}</div>
                                        </td>
                                        <td>
                                            <p className="mb-0 small"><strong>City:</strong> {report.city}</p>
                                            <p className="mb-0 small text-muted"><strong>Dist:</strong> {report.district || "N/A"}</p>
                                        </td>
                                        <td>
                                            <div className="small">
                                                <div>Comp: <span className="text-success fw-bold">{report.tasksCompleted || 0}</span></div>
                                                <div>Pend: <span className="text-warning fw-bold">{report.pendingTasks || 0}</span></div>
                                            </div>
                                        </td>
                                        <td>
                                            <span className={`badge ${
                                                report.status === 'Validated' ? 'bg-success' : 
                                                report.status === 'Rejected' ? 'bg-danger' : 
                                                'bg-info'
                                            } bg-opacity-10 text-${
                                                report.status === 'Validated' ? 'success' : 
                                                report.status === 'Rejected' ? 'danger' : 
                                                'info'
                                            } border`}>
                                                {report.status}
                                            </span>
                                        </td>
                                        <td className="pe-4 text-end">
                                            <div className="d-flex gap-2 justify-content-end">
                                                <button 
                                                    className="btn btn-sm btn-outline-danger" 
                                                    onClick={() => downloadPDF(report)}
                                                    title="Download as PDF"
                                                >
                                                    <i className="fas fa-file-pdf" />
                                                </button>
                                                <button 
                                                    className="btn btn-sm btn-primary px-3" 
                                                    onClick={() => setResponseForm({ id: report._id, status: report.status, response: report.adminResponse || "" })}
                                                >
                                                    Respond
                                                </button>
                                                <button 
                                                    className="btn btn-sm btn-outline-secondary" 
                                                    onClick={() => handleDelete(report._id)}
                                                    title="Delete Report"
                                                >
                                                    <i className="fas fa-trash-alt" />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {responseForm.id && (
                <div className="modal d-block" style={{ background: "rgba(0,0,0,0.5)" }}>
                    <div className="modal-dialog modal-dialog-centered">
                        <div className="modal-content border-0 shadow-lg">
                            <form onSubmit={handleRespond}>
                                <div className="modal-header">
                                    <h5 className="modal-title fw-bold">Respond to Report</h5>
                                    <button type="button" className="btn-close" onClick={() => setResponseForm({ id: null, status: "", response: "" })}></button>
                                </div>
                                <div className="modal-body">
                                    <div className="mb-3">
                                        <label className="form-label small fw-bold">Update Status</label>
                                        <select 
                                            className="form-select" 
                                            value={responseForm.status} 
                                            onChange={(e) => setResponseForm({ ...responseForm, status: e.target.value })}
                                            required
                                        >
                                            <option value="Pending">Pending</option>
                                            <option value="Reviewed">Reviewed</option>
                                            <option value="Validated">Validated</option>
                                            <option value="Rejected">Rejected</option>
                                        </select>
                                    </div>
                                    <div className="mb-3">
                                        <label className="form-label small fw-bold">Admin Feedback / Response</label>
                                        <textarea 
                                            className="form-control" 
                                            rows="4" 
                                            placeholder="Provide feedback to the MC..."
                                            value={responseForm.response}
                                            onChange={(e) => setResponseForm({ ...responseForm, response: e.target.value })}
                                            required
                                        />
                                    </div>
                                </div>
                                <div className="modal-footer">
                                    <button type="button" className="btn btn-light" onClick={() => setResponseForm({ id: null, status: "", response: "" })}>Cancel</button>
                                    <button type="submit" className="btn btn-primary">Save Response</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default AdminReports;
